spring:  
  cloud: 
    stream:
      poller:
        fixed-delay: ${jvwatch.checkTask.period} 
      function:
        definition: vaccineClinicDataSupplier;vaccineClinicDataSink
      bindings: 
        vaccineClinicDataSupplier-out-0: 
          destination: jvwatch-clinic-data
        vaccineClinicDataSink-in-0: 
          destination: jvwatch-clinic-data
          group: jvwatch-clinic-data-sink-group
          consumer:
            concurrency: 1    
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000  

